name: simple-cell
version: '2.7.0.0'
synopsis: Batch Processing of resumable states
description: SimpleCell uses SimpleStore and self generating keys to create batch operations on datatypes
category: DB
author: Scott <scott.murphy@plowtech.net>
maintainer: Scott <scott.murphy@plowtech.net>
copyright: 2017 Plow Technologies
license: BSD3
github: plow-technologies/simple-cell

flags:
  rebench:
    description: Setup second run for profiling
    manual: false
    default: false

library:
  source-dirs: src
  exposed-modules:      
  - SimpleStore.Cell                    
  other-modules:        
  - SimpleStore.Cell.Internal
  - SimpleStore.Cell.Types
  - SimpleStore.Cell.DIG
  - SimpleStore.Cell.TH
  - SimpleStore.Cell.TH.StoreMakers
  dependencies:
  - aeson >= 0.7.0
  - aeson-serialize >= 0.0.0
  - async >= 2.0.0
  - base >=4.7 && <5
  - basic-prelude >= 0.3.0                      
  - bytestring >= 0.10.0.2
  - cereal >= 0.4.0.1                      
  - containers >= 0.5.0.0
  - directed-keys >= 0.3.1
  - hashable >= 1.2.2.0
  - list-t >= 0.3.0
  - mtl >= 2.1.3.1
  - plow-extras-list >= 0.1.0
  - simple-store == 4.0.0
  - stm >= 2.4.3
  - stm-containers >= 0.2.7 
  - system-fileio >= 0.3.12
  - system-filepath >= 0.4.10
  - template-haskell 
  - text >= 1.1.0.1
  ghc-options:          
  - -Wall
  - -Werror

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - aeson
    - aeson-serialize
    - base >= 4.7 && <5
    - cereal
    - directed-keys
    - hashable
    - hspec
    - QuickCheck >= 2.7.6
    - simple-cell
    - simple-store
    - text
    ghc-options:          
    - -Wall
    - -Werror    

benchmarks:
  simple-cell-bench:
    main: Bench.hs
    source-dirs: 
    - bench
    - test
    dependencies:
    - aeson
    - aeson-serialize
    - base >= 4.7 && <5
    - cereal
    - criterion
    - directed-keys
    - hashable
    - hspec
    - QuickCheck >= 2.7.6
    - simple-cell
    - simple-store
    - text
    when:
    - condition: flag(rebench)
      then:
        ghc-options:
        - -threaded
        - -Wall
        - -rtsopts
        - -prof
        - -auto-all
        - -caf-all
        - -osuf p_o 
        - -hisuf p_hi
      else:
        ghc-options:
        - -threaded 
        - -Wall  
        - -rtsopts 
        - -fllvm 
        - -static
