flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:plow-technologies/plow-extras.git
    commit: 1caf66300dccb79681f71be046a14ce566526964
  subdirs:
  - plow-extras-time
  - plow-extras-lens
  - plow-extras-aeson
  - plow-extras-list
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/directed-keys.git
    commit: 4cbcbd9cd391474452f47c780097e25463c00985
  extra-dep: true
- location: https://plow:EGe8TELsBW@hackage.plowtech.net/package/simple-store-0.2.0/simple-store-0.2.0.tar.gz
  subdirs: []
  extra-dep: true
- location: https://plow:EGe8TELsBW@hackage.plowtech.net/package/simple-cell-types-0.11.0/simple-cell-types-0.11.0.tar.gz
  subdirs: []
  extra-dep: true
extra-deps:
- aeson-1.0.2.1
- aeson-serialize-0.0.0
- compressed-3.0.3
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- serial-test-generators-0.1.3
resolver: lts-7.4
