flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:plow-technologies/plow-extras.git
    commit: 1caf66300dccb79681f71be046a14ce566526964
  subdirs:
  - plow-extras-time
  - plow-extras-lens
  - plow-extras-aeson
  - plow-extras-list
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/directed-keys.git
    commit: 62be50d36b38f62db3afe6e7c5dc507b92a66014
  extra-dep: true
- location:
    git: https://github.com/plow-technologies/simple-store.git
    commit: 4388322a43674a0774e42db1738f653ead1cc9ab
  extra-dep: true
extra-deps:
- aeson-serialize-0.0.0
- compressed-3.0.3
- serial-test-generators-0.1.3
resolver: lts-7.4
